// <auto-generated />
using System;
using MRO.SKM.Docu.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRO.SKM.Docu.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251212161224_AddedThinkingBudget")]
    partial class AddedThinkingBudget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MRO.SKM.SDK.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanThrowException")
                        .HasColumnType("bit");

                    b.Property<Guid>("CodeFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasParameters")
                        .HasColumnType("bit");

                    b.Property<bool>("HasReturnValue")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodeFileId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.CodeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("CodeFiles");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.Method", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanThrowException")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasParameters")
                        .HasColumnType("bit");

                    b.Property<bool>("HasReturnValue")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.RepositoryAiConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GenerateDoc")
                        .HasColumnType("bit");

                    b.Property<string>("GenerateDocPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GenerateGuide")
                        .HasColumnType("bit");

                    b.Property<int>("GenerateGuideFileCount")
                        .HasColumnType("int");

                    b.Property<string>("GenerateGuideFileExtensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenerateGuideFilePickMethod")
                        .HasColumnType("int");

                    b.Property<string>("GenerateGuidePrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenerateGuideThinkingBudget")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("RepositoryAiConfigurations");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.RepositoryLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("RepositoryLanguages");
                });

            modelBuilder.Entity("MRO.SMK.SDK.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceProviderConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceProviderService")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.Class", b =>
                {
                    b.HasOne("MRO.SKM.SDK.Models.CodeFile", "CodeFile")
                        .WithMany("Classes")
                        .HasForeignKey("CodeFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeFile");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.CodeFile", b =>
                {
                    b.HasOne("MRO.SMK.SDK.Models.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.Method", b =>
                {
                    b.HasOne("MRO.SKM.SDK.Models.Class", "Class")
                        .WithMany("Methods")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.RepositoryAiConfiguration", b =>
                {
                    b.HasOne("MRO.SMK.SDK.Models.Repository", "Repository")
                        .WithMany("RepositoryAiConfigurations")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.RepositoryLanguage", b =>
                {
                    b.HasOne("MRO.SMK.SDK.Models.Repository", "Repository")
                        .WithMany("Languages")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.Class", b =>
                {
                    b.Navigation("Methods");
                });

            modelBuilder.Entity("MRO.SKM.SDK.Models.CodeFile", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("MRO.SMK.SDK.Models.Repository", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("RepositoryAiConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
