//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRO.SKM.Google.Gemini {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRO.SKM.Google.Gemini.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist ein Senior Programmierer.
        ///Deine Aufgabe ist es detaillierte Kommentare für Code zu erstellen.
        ///Erstelle eine Beschreibung für den folgenden Codeausschnit:
        ///
        ///&lt;Code&gt;
        ///
        ///Beschränke deine Antwort auf das Element &quot;&lt;ElementName&gt;&quot;.
        ///
        ///Antworte auf Deutsch..
        /// </summary>
        internal static string GenerateDocumentation {
            get {
                return ResourceManager.GetString("GenerateDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle anhand der verfügbaren Dateien einen detaillierten Styleguide für Entwickler. 
        ///
        ///Antworte mit HTML und CSS Code, damit deine Antwort direkt in einer Webseite dargestellt werden kann.
        ///Also Frontend-Framework für den Styleguide steht dir Bootstrap zur Verfügung. Das Projekt, über welches du den Styleguide erstellen sollst, verwendet kein Bootstrap im Frontend.
        ///Du musst Bootstrap nicht erneut mit &lt;script&gt; oder &lt;style&gt; einbinden. 
        ///
        ///Wenn du CSS-Klassen verwendest, stelle sicher dass deine CSS-Klass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateGuide {
            get {
                return ResourceManager.GetString("GenerateGuide", resourceCulture);
            }
        }
    }
}
